name: tfm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - optuna
  - jupyter
  - numpy
  - shap
  - matplotlib
  - ipykernel
  - seaborn
  - pandas
  - scikit-learn
  - optuna-integration
  - fastparquet
  - r-base
  - r-essentials
  - rstudio