name: tfm_r
channels:
  - conda-forge
  - defaults
dependencies:
  - r-base
  - r-essentials
  - r-haven
  - r-labelled
  - r-arrow
  - r-data.table
  - r-scales
  - r-car
  - r-broom
  - r-skimr
  - r-irkernel
  - r-here
