name: tfm_python
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyter
  - ipykernel
  - numpy
  - pandas
  - fastparquet
  - matplotlib
  - seaborn
  - scikit-learn
  - optuna
  - optuna-integration
  - shap
  - pip
